---
pci_passthrough_filter: .*\b(?:NVIDIA|Audio)\b.*

wireguard_ipv4: 192.168.196.10

wireguard_direct_interface: enp5s0
wireguard_direct_mac: 98:b7:85:21:e9:63
wireguard_direct_mtu: 9000
wireguard_direct_address: 192.168.197.1/31
wireguard_direct_endpoint: 192.168.197.1:51820
wireguard_direct_peer: nas.local
wireguard_direct_peer_address: 192.168.197.0

pod_cidr: 10.42.3.0/24

lhstor_mode: macvlan
lhstor_subnet: 192.168.198.0/24
lhstor_range_start: 192.168.198.16
lhstor_range_end: 192.168.198.31
lhstor_shim_address: 192.168.198.10/24
