---
wireguard_ipv4: 192.168.196.8

wireguard_direct_interface: enp1s0
wireguard_direct_mac: 98:b7:85:8a:1c:ae
wireguard_direct_mtu: 9000
wireguard_direct_address: 192.168.197.0/31
wireguard_direct_endpoint: 192.168.197.0:51820
wireguard_direct_peer: desktop.local
wireguard_direct_peer_address: 192.168.197.1

pod_cidr: 10.42.4.0/24

lhstor_mode: macvlan
lhstor_subnet: 192.168.198.0/24
lhstor_range_start: 192.168.198.32
lhstor_range_end: 192.168.198.47
lhstor_shim_address: 192.168.198.8/24
