---
k3s_server_args_common: "
    {{ default_k3s_server_args }}
    --node-external-ip {{ ansible_default_ipv4.address }}
    --node-label svccontroller.k3s.cattle.io/enablelb=true
    --node-label k8s.arl.sh/type=cloud
    --node-label k8s.arl.sh/cloud=ovh
    --node-label k8s.arl.sh/cpu=intel-atom-n2800
    --node-label k8s.arl.sh/bandwidth-up=100
    --node-label k8s.arl.sh/bandwidth-down=100
    --node-label node.longhorn.io/disable-v2-data-engine=true
  "

k3s_server_join_url: "https://{{ groups['k3s_server'][(groups['k3s_server'].index(inventory_hostname) + 1) % (groups['k3s_server'] | length)] }}:6443"

install_k3s_server_args: "{{ k3s_server_args_common }} --server {{ k3s_server_join_url }}"

server_init_args: >-
  {% if ansible_host == first_server %}
    --cluster-init
    --tls-san {{ apiserver_endpoint }}
  {% else %}
    --server https://{{ first_server }}:6443
  {% endif %}
  --token {{ k3s_token }}
  {{ k3s_server_args_common }}
